In [53]:
import torch
import numpy as np

In [54]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [55]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [56]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3425, 0.5821],
        [0.1245, 0.4075]]) 



In [57]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4395, 0.7437, 0.3335],
        [0.0763, 0.7386, 0.1613]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [58]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [59]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    print('moving to GPU')
    tensor = tensor.to("cuda")

moving to GPU


In [60]:
tensor = torch.rand(3, 3)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([0.3931, 0.6736, 0.2023])
First column: tensor([0.3931, 0.8392, 0.1023])
Last column: tensor([0.2023, 0.0055, 0.9326])
tensor([[0.3931, 0.0000, 0.2023],
        [0.8392, 0.0000, 0.0055],
        [0.1023, 0.0000, 0.9326]])


In [61]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.3931, 0.0000, 0.2023, 0.3931, 0.0000, 0.2023, 0.3931, 0.0000, 0.2023],
        [0.8392, 0.0000, 0.0055, 0.8392, 0.0000, 0.0055, 0.8392, 0.0000, 0.0055],
        [0.1023, 0.0000, 0.9326, 0.1023, 0.0000, 0.9326, 0.1023, 0.0000, 0.9326]])


In [62]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1.5451e-01, 0.0000e+00, 4.0943e-02],
        [7.0431e-01, 0.0000e+00, 3.0036e-05],
        [1.0472e-02, 0.0000e+00, 8.6975e-01]])

In [63]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cuda device


In [64]:
torch.backends.mps.is_available()

False

In [65]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms


In [66]:

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [67]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [68]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([2], device='cuda:0')


In [69]:
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [70]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [71]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [72]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[-0.7324,  0.1291, -0.2578, -0.2977,  0.1748, -0.1352,  0.0988, -0.4846,
          0.4597, -0.0509, -0.5924, -0.3553, -0.2915, -0.1084, -0.2740, -0.0607,
         -0.5383, -0.3178,  0.0878, -0.1155],
        [-0.8773,  0.0249, -0.4146, -0.3834, -0.4735, -0.0423, -0.3856, -0.2850,
          0.2927, -0.3393, -0.7443, -0.1967, -0.0757,  0.1157,  0.0533, -0.1033,
         -0.4302, -0.3440,  0.2408, -0.3635],
        [-1.1960,  0.2838, -0.5581, -0.4902,  0.1255, -0.1372,  0.1660, -0.2095,
         -0.0623,  0.0820, -0.3668, -0.6999,  0.4379,  0.3749, -0.2282,  0.0309,
         -0.3812, -0.0197,  0.1773, -0.7132]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.0000, 0.1291, 0.0000, 0.0000, 0.1748, 0.0000, 0.0988, 0.0000, 0.4597,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0878, 0.0000],
        [0.0000, 0.0249, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2927,
         0.0000, 0.0000, 0.0000, 0.0000, 0.1157, 0.05

In [73]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)

In [74]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

In [76]:
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[-0.0029,  0.0091,  0.0232,  ...,  0.0268, -0.0259, -0.0146],
        [ 0.0235, -0.0002,  0.0171,  ..., -0.0161,  0.0154,  0.0014]],
       device='cuda:0', grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([ 0.0328, -0.0291], device='cuda:0', grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[ 0.0303,  0.0367,  0.0442,  ..., -0.0110,  0.0390,  0.0013],
        [-0.0374,  0.0386, -0.0252,  ...,  0.0021,  0.0024,  0.0354]],
       device='cuda:0', grad_fn=<Sl